dist: trusty
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar
  - $HOME/.sonarscanner
script:
- mvn clean test jacoco:report
  #coveralls:report
#- npm run build --prefix frontend/
- sonar-scanner
before_script:
#- npm install --prefix frontend/
addons:
  sonarcloud:
    organization: rage2002-github
    token: b576f6bcad19cda33b05a838ce79db2f8255d540
